server:
  port: 8081

spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a_mysql
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl